CREATE TABLE ENSEIGNANT_COPY
AS (SELECT * FROM ENSEIGNANT);
INSERT INTO ENSEIGNANT_COPY (ID, DATE_ENTREE, PRENOM, NOM, EMAIL)
VALUES (1, TO_DATE('2024/07/02', 'YYYY/MM/DD'), 'Robert', 'Valée', 'R.valee@gmail.com');
INSERT INTO ENSEIGNANT_COPY (ID, DATE_ENTREE, NOM, PRENOM, EMAIL)
VALUES (2, TO_DATE('2024/07/03', 'YYYY/MM/DD'), 'Gilles', 'Edouard', 'G.Edouard@gmail.com');
INSERT INTO ENSEIGNANT_COPY (ID, DATE_ENTREE, NOM, PRENOM, EMAIL)
VALUES (3, TO_DATE('2024/07/02', 'YYYY/MM/DD'), 'Allain', 'Chausson', 'A.chausson@gmail.com');
INSERT INTO ENSEIGNANT_COPY (ID, DATE_ENTREE, NOM, PRENOM, EMAIL)
VALUES (4, TO_DATE('2024/07/01', 'YYYY/MM/DD'), 'Allize', 'Shaefer', 'A.sheafer@gmail.com');
INSERT INTO ENSEIGNANT_COPY (ID, DATE_ENTREE, NOM, PRENOM, EMAIL)
VALUES (5, TO_DATE('2024/07/07', 'YYYY/MM/DD'), 'Jules', 'Bon', 'J.bon@gmail.com');


CREATE TABLE ETUDIANT_COPY
AS (SELECT * FROM ETUDIANT);
INSERT INTO ETUDIANT_COPY (ID,PRENOM,NOM,EMAIL,PROMO_NOM,PROMO_ANNEE)
VALUES (1,'Barbe','Roatta','B.roatta@gmail.com','3e5',2024);
INSERT INTO ETUDIANT_COPY (ID,NOM,PRENOM,EMAIL,PROMO_NOM,PROMO_ANNEE)
VALUES (2,'Alexandra','Beaubois','A.beaubois@gmail.com','3e5',2024);
INSERT INTO ETUDIANT_COPY (ID,NOM,PRENOM,EMAIL,PROMO_NOM,PROMO_ANNEE)
VALUES (3,'Loïc','Link','L.link@gmail.com','3e5',2024);
INSERT INTO ETUDIANT_COPY (ID,NOM,PRENOM,EMAIL,PROMO_NOM,PROMO_ANNEE)
VALUES (4,'Tania','Passereau','T.passereau@gmail.com','4e4',2024);
INSERT INTO ETUDIANT_COPY (ID,NOM,PRENOM,EMAIL,PROMO_NOM,PROMO_ANNEE)
VALUES (5,'Valentin','Buchi','V.buchi@gmail.com','4e4',2024);
INSERT INTO ETUDIANT_COPY (ID,NOM,PRENOM,EMAIL,PROMO_NOM,PROMO_ANNEE)
VALUES (6,'Paul','Bougie','P.bougie@gmail.com','4e4',2024);

CREATE TABLE PROMO_COPY
AS (SELECT * FROM PROMO);
INSERT INTO PROMO_COPY (NOM,ANNEE)
VALUES ('3e5',2024);
INSERT INTO PROMO_COPY (NOM,ANNEE)
VALUES ('4e4',2024);
INSERT INTO PROMO_COPY (NOM,ANNEE)
VALUES ('4e4',2023);

CREATE TABLE RETARD_COPY
AS (SELECT * FROM RETARD);
INSERT INTO RETARD_COPY (ID,ETUDIANT_ID,DATE_RETARD,RETARD,JUSTIFICATION)
VALUES (1,3,TO_DATE('2024/07/05', 'YYYY/MM/DD'),INTERVAL '18' MINUTE,NULL);
INSERT INTO RETARD_COPY (ID,ETUDIANT_ID,DATE_RETARD,RETARD,JUSTIFICATION)
VALUES (1,3,TO_DATE('2024/07/06', 'YYYY/MM/DD'),INTERVAL '16' MINUTE,NULL);
INSERT INTO RETARD_COPY (ID,ETUDIANT_ID,DATE_RETARD,RETARD,JUSTIFICATION)
VALUES (1,3,TO_DATE('2024/07/07', 'YYYY/MM/DD'),INTERVAL '19' MINUTE,NULL);
INSERT INTO RETARD_COPY (ID,ETUDIANT_ID,DATE_RETARD,RETARD,JUSTIFICATION)
VALUES (1,3,TO_DATE('2024/07/10', 'YYYY/MM/DD'),INTERVAL '5' MINUTE,NULL);
INSERT INTO RETARD_COPY (ID,ETUDIANT_ID,DATE_RETARD,RETARD,JUSTIFICATION)
VALUES (1,4,TO_DATE('2024/07/05', 'YYYY/MM/DD'),INTERVAL '3' MINUTE,'médicale');

CREATE TABLE MATIERE_COPY
AS (SELECT * FROM MATIERE);
INSERT INTO MATIERE_COPY (NOM)
VALUES ('Math');
INSERT INTO MATIERE_COPY (NOM)
VALUES ('SVT');

CREATE TABLE ENSEIGNANT_MATIERE_COPY
AS (SELECT * FROM ENSEIGNANT_MATIERE);
INSERT INTO ENSEIGNANT_MATIERE_COPY (ENSEIGNANT_ID,MATIERE_NOM)
VALUES (2,'Math');
INSERT INTO ENSEIGNANT_MATIERE_COPY (ENSEIGNANT_ID,MATIERE_NOM)
VALUES (3,'Math');
INSERT INTO ENSEIGNANT_MATIERE_COPY (ENSEIGNANT_ID,MATIERE_NOM)
VALUES (4,'Math');
INSERT INTO ENSEIGNANT_MATIERE_COPY (ENSEIGNANT_ID,MATIERE_NOM)
VALUES (5,'SVT');
INSERT INTO ENSEIGNANT_MATIERE_COPY (ENSEIGNANT_ID,MATIERE_NOM)
VALUES (6,'SVT');

CREATE TABLE ETUDIANT_PROMO_COPY
AS (SELECT * FROM ETUDIANT_PROMO);
INSERT INTO ETUDIANT_PROMO_COPY (ETUDIANT_ID,PROMO_NOM,PROMO_ANNEE)
VALUES (3,'3e5',2024);
INSERT INTO ETUDIANT_PROMO_COPY (ETUDIANT_ID,PROMO_NOM,PROMO_ANNEE)
VALUES (4,'4e4',2023);
INSERT INTO ETUDIANT_PROMO_COPY (ETUDIANT_ID,PROMO_NOM,PROMO_ANNEE)
VALUES (1,'3e5',2024);
INSERT INTO ETUDIANT_PROMO_COPY (ETUDIANT_ID,PROMO_NOM,PROMO_ANNEE)
VALUES (2,'3e5',2024);
INSERT INTO ETUDIANT_PROMO_COPY (ETUDIANT_ID,PROMO_NOM,PROMO_ANNEE)
VALUES (3,'3e5',2024);
INSERT INTO ETUDIANT_PROMO_COPY (ETUDIANT_ID,PROMO_NOM,PROMO_ANNEE)
VALUES (5,'4e4',2024);
INSERT INTO ETUDIANT_PROMO_COPY (ETUDIANT_ID,PROMO_NOM,PROMO_ANNEE)
VALUES (6,'4e4',2024);

CREATE TABLE NOTE_COPY
AS (SELECT * FROM NOTE);
INSERT INTO NOTE_COPY (ID,ENSEIGNANT_ID,MATIERE_NOM,ETUDIANT_ID,DATE_NOTE,NOTE)
VALUES (1,1,'Math',2,TO_DATE('2024/07/15', 'YYYY/MM/DD'),18);
INSERT INTO NOTE_COPY (ID,ENSEIGNANT_ID,MATIERE_NOM,ETUDIANT_ID,DATE_NOTE,NOTE)
VALUES (2,2,'Math',2,TO_DATE('2024/07/15', 'YYYY/MM/DD'),17);
INSERT INTO NOTE_COPY (ID,ENSEIGNANT_ID,MATIERE_NOM,ETUDIANT_ID,DATE_NOTE,NOTE)
VALUES (3,3,'Math',2,TO_DATE('2024/07/15', 'YYYY/MM/DD'),14);
INSERT INTO NOTE_COPY (ID,ENSEIGNANT_ID,MATIERE_NOM,ETUDIANT_ID,DATE_NOTE,NOTE)
VALUES (4,4,'Math',2,TO_DATE('2024/07/15', 'YYYY/MM/DD'),10);
INSERT INTO NOTE_COPY (ID,ENSEIGNANT_ID,MATIERE_NOM,ETUDIANT_ID,DATE_NOTE,NOTE)
VALUES (5,5,'Math',2,TO_DATE('2024/07/15', 'YYYY/MM/DD'),12);
INSERT INTO NOTE_COPY (ID,ENSEIGNANT_ID,MATIERE_NOM,ETUDIANT_ID,DATE_NOTE,NOTE)
VALUES (6,6,'Math',2,TO_DATE('2024/07/15', 'YYYY/MM/DD'),19);
INSERT INTO NOTE_COPY (ID,ENSEIGNANT_ID,MATIERE_NOM,ETUDIANT_ID,DATE_NOTE,NOTE)
VALUES (7,1,'SVT',4,TO_DATE('2024/07/17', 'YYYY/MM/DD'),18);
INSERT INTO NOTE_COPY (ID,ENSEIGNANT_ID,MATIERE_NOM,ETUDIANT_ID,DATE_NOTE,NOTE)
VALUES (8,2,'SVT',4,TO_DATE('2024/07/17', 'YYYY/MM/DD'),5);
INSERT INTO NOTE_COPY (ID,ENSEIGNANT_ID,MATIERE_NOM,ETUDIANT_ID,DATE_NOTE,NOTE)
VALUES (9,3,'SVT',4,TO_DATE('2024/07/17', 'YYYY/MM/DD'),7);
