SELECT E.NOM AS "Nom", E.PRENOM AS "Prenom", R.DATE_RETARD AS "Date du retard", R.RETARD AS "Durée du retard"
FROM RETARD R
JOIN ETUDIANT E ON R.ETUDIANT_ID = E.ID
WHERE R.RETARD > INTERVAL '10' MINUTE AND R.JUSTIFICATION IS NULL
ORDER BY R.RETARD DESC;