SELECT 
    E.NOM AS "NOM DE L ETUDIANT",
    E.PRENOM AS "PRENOM DE L ETUDIANT",
    P.EMAIL AS "MAIL DU PROFESSEUR",
    N.MATIERE_NOM AS "MATIERE",
    N.NOTE AS "NOTE"
FROM NOTE N
JOIN ETUDIANT E ON N.ETUDIANT_ID = E.ID
JOIN ENSEIGNANT P ON N.ENSEIGNANT_ID = P.ID
WHERE N.NOTE >= 15
ORDER BY N.NOTE DESC;