DROP TABLE Enseignant CASCADE CONSTRAINTS;
DROP TABLE Matiere CASCADE CONSTRAINTS;
DROP TABLE Promo CASCADE CONSTRAINTS;
DROP TABLE Etudiant CASCADE CONSTRAINTS;
DROP TABLE Enseignant_Matiere CASCADE CONSTRAINTS;
DROP TABLE Retard CASCADE CONSTRAINTS;
DROP TABLE Etudiant_Promo CASCADE CONSTRAINTS;
DROP TABLE Note CASCADE CONSTRAINTS;

CREATE TABLE Enseignant
AS (SELECT * FROM ENSEIGNANT_COPY);
CREATE TABLE Matiere
AS (SELECT * FROM Matiere_COPY);
CREATE TABLE Promo
AS (SELECT * FROM Promo_COPY);
CREATE TABLE Etudiant
AS (SELECT * FROM Etudiant_COPY);
CREATE TABLE Enseignant_Matiere
AS (SELECT * FROM Enseignant_Matiere_COPY);
CREATE TABLE Retard
AS (SELECT * FROM Retard_COPY);
CREATE TABLE Etudiant_Promo
AS (SELECT * FROM Etudiant_Promo_COPY);
CREATE TABLE Note
AS (SELECT * FROM Note_COPY);

DROP TABLE Enseignant_COPY CASCADE CONSTRAINTS;
DROP TABLE Matiere_COPY CASCADE CONSTRAINTS;
DROP TABLE Promo_COPY CASCADE CONSTRAINTS;
DROP TABLE Etudiant_COPY CASCADE CONSTRAINTS;
DROP TABLE Enseignant_Matiere_COPY CASCADE CONSTRAINTS;
DROP TABLE Retard_COPY CASCADE CONSTRAINTS;
DROP TABLE Etudiant_Promo_COPY CASCADE CONSTRAINTS;
DROP TABLE Note_COPY CASCADE CONSTRAINTS;